//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoCentral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int idRespuesta { get; set; }
        public string nombre { get; set; }
        public string respuesta1 { get; set; }
        public int consultaId { get; set; }
    
        public virtual Consulta Consulta { get; set; }
    }
}
